import "~/styles/globals.css";

import React from 'react';

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "START Gallery",
  description: "Generated by START",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between w-full p-4 text-xl font-semibold">
      <div>Gallery</div>

      <div>Sign In</div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div> {/* Wrap the JSX expressions inside a div */}
      <html lang="en">
      </html> {/* Add closing tag for the html element */}
      <body className={`${GeistSans.variable} flex flex-col gap-4`}>
        <TopNav />
        {children}
      </body>
    </div>
  );
}
